services:
  member-id:
    image: 'ghcr.io/neuland-ingolstadt/member-id-backend:latest'
    container_name: member-id-server
    ports:
      - '8000:8000'
    environment:
      - 'RUST_LOG=${RUST_LOG:-info}'
      - 'QR_PRIVATE_KEY_HEX=${QR_PRIVATE_KEY_HEX}'
      - 'JWKS_URL=${JWKS_URL}'
      - 'EXPECTED_AUDIENCE=${EXPECTED_AUDIENCE}'
      - 'PKPASS_ORGANIZATION_NAME=${PKPASS_ORGANIZATION_NAME}'
      - 'PKPASS_PASS_TYPE_IDENTIFIER=${PKPASS_PASS_TYPE_IDENTIFIER}'
      - 'PKPASS_TEAM_IDENTIFIER=${PKPASS_TEAM_IDENTIFIER}'
      - 'PKPASS_SIGN_CERT_PATH=${PKPASS_SIGN_CERT_PATH}'
      - 'PKPASS_SIGN_KEY_PATH=${PKPASS_SIGN_KEY_PATH}'
      - 'PKPASS_BEACON_PROXIMITY_UUID=${PKPASS_BEACON_PROXIMITY_UUID}'
    volumes:
      - ./certs:/app/certs:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s
